# Generated by Django 2.1.2 on 2018-10-03 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(help_text='The date the patch was created')),
                ('version_number', models.CharField(help_text='a string representation of a patch version', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
